project:
  type: website
  resources:
    - googlec46eb400cb975613.html

website:
  title: "STAT2001 Revision Summaries"
  repo-url: https://github.com/Isaac7777-cpu/stat2001-summaries
  repo-actions: [edit, source, issue]
  repo-branch: master
  # repo-subdir: stat3011-lecture-notes/
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    style: "docked"
    background: dark
    collapse-level: 1
    contents:
      - text: "CH02 : Probability"
        href: contents/chapter-02/index.qmd
      - section: "CH03 : Discrete R.V."
        href: contents/chapter-03/index.qmd
        contents:
          - contents/chapter-03/1rv.qmd
          - contents/chapter-03/2measures.qmd
      - section: "CH04 : Continuous R.V."
        href: contents/chapter-04/index.qmd
        contents:
          - contents/chapter-04/1rv.qmd
          - contents/chapter-04/2measures.qmd
      - section: "CH05 : Multivariate Distributions"
        href: contents/chapter-05/index.qmd
        contents:
          - contents/chapter-05/01-distributions.qmd
          - contents/chapter-05/02-continuous-joint-probability-and-expectations-2.qmd
      - text: "CH06 : Functions of Random Variables"
        href: contents/chapter-06/index.qmd
      - section: "CH07 : Sampling Distributions and Central Limit Theorem"
        href: contents/chapter-07/index.qmd
        contents:
          - contents/chapter-07/sums-of-continuous-random-variables.qmd
      - section: "CH08 : Estimation"
        href: contents/chapter-08/index.qmd
        contents:
          - contents/chapter-08/interval-estimate.qmd
          - contents/chapter-08/monte-carle-method.qmd
          - contents/chapter-08/point-estimate.qmd
  page-footer:
    left: "Copyright 2025, Isaac Leong"
    right:
      - icon: github
        href: https://github.com/Isaac7777-cpu/stat2001-summaries
      - icon: linkedin
        href: https://www.linkedin.com/in/isaac-leong-40b3b6276?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BQ7KeJzrBS6Kd8acL8AxrAw%3D%3D
format:
  html:
    include-in-header: 
      - scripts/mathjax.html
      - scripts/mathjax-macros.html  # this is auto-generated macro extension
    theme:
      light:
        - lux
        - brand
      dark:
        - cyborg
        - brand
        - ./scripts/custom-dark.scss
    css: styles.css
    toc: true
    toc-expand: 1
    number-sections: true
    fig-align: center
    code-fold: true
    code-summary: "Show the code"
    code-results: hold

execute: 
  freeze: auto
  cache: true

scripts:
  pre-render: scripts/convert_macros.sh
    
