---
title: "Discrete R.V."
---

# Random Variable

::: {#def-random-variable}

A _random variable_ (rv) is a numerical variable whose value depends on the outcome of an experiment.

:::

A random variable must be a number; it cannot be a letter, say. More precisely, a random variable is a "real-valued function for which the domain is a sample space". 

::: {#exm-rv}

A coin is tossed twice and the sequence of $H$'s and $T$'s is observed. Let $Y$ be the number of $H$'s which come up. Show that $Y$ is a random variable. The experiment here has 4 possible outcomes: $TT$, $TH$, $HT$, $HH$.

$Y = 0$ if the outcome is $TT$  
$Y = 1$ if the outcome is $TH$ or $HT$  
$Y = 2$ if the outcome is $HH$

:::

## Probability Distribution

The probability that a discrete random variable $Y$ takes on a particular value $y$ is the sum of the probabilities of all sample points in the sample space $S$ that are associated with $y$.

We write this probability $P(Y = y)$.

The probability distribution of a discrete random variable $Y$ is any information which provides $P(Y = y)$ for each possible value $y$ of $Y$. This information may take the form of a list, table function (formula) or graph.

## Probability Mass Function

It is conventional to denote rv's by upper case letters (e.g., $Y$, $X$, $U$) and possible values of those rv's by the corrsponding lower case letters (e.g., $y$, $x$, $u$).

$P(Y = y)$ is called the _probability mass function_ (pmf) of $Y$ and is often written $p(y)$ or $p_Y(y)$.

### Two Properties of Discrete PMF's

1. $0 \leq p(y) \leq 1$  for all $y$
2. $\sum_y p(y) = 1$

---

::: {#exm-3}

A coin is repeatedly tossed until the first head comes up. Let $Y$ be the number of tosses. Derive the pmf of $Y$, and check that it satisfies the two properties of discrete pmf's.

Then $Y$ has pmf,
$$
p(y) = \left( \frac{1}{2} \right)^y
$$

We should also observe that Property 1 is satisfied, since 1/2, 1/4, 1/8, ... are all between o and 1. Also,

$$
\sum_y p(y) = \frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \cdots = 1
$$

Thus Property 2 is also satisfied.

$Y$ is a discrete rv in this example because $\{1,2,3,\ldots\}$ is a countably infinite set (its elements can be listed). A pmf uniquely defines a rv or pr dsn. Thus a rv can
t have 2 or more different pmf's. Note that not all functions are valid pmf's.

:::

---