name: Auto Sidebar Updater
permissions: 
  contents: write

on:
  push:
    paths:
      - 'contents/**'
      - 'scripts/grab_contents.sh'
      - 'edit-quarto-yaml.sh'

jobs:
  update-sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Make script executable and run sidebar update
        run: |
          chmod +x scripts/grab_contents_v2.sh
          chmod +x scripts/edit-quarto-yaml.sh
          bash scripts/edit-quarto-yaml.sh
        id: update_sidebar

      - name: Commit and push if sidebar changed
        if: ${{ hashFiles('__autogen/sidebar-changed.flag') != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add _quarto.yml
          git commit -m "Auto-update sidebar from contents/" || echo "Nothing to commit"
          git push origin HEAD

      - name: Cleanup marker
        if: ${{ hashFiles('__autogen/sidebar-changed.flag') != '' }}
        run: rm -f __autogen/sidebar-changed.flag

      - name: Upload sidebar artifacts
        if: ${{ hashFiles('__autogen/sidebar-changed.flag') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: sidebar-autogen
          path: |
            _quarto.yml
            __autogen/